language: objective-c
osx_image: xcode9.2
branches:
    only:
        - master
env:
    global:
        - LC_CTYPE=en_US.UTF-8
        - LANG=en_US.UTF-8
        - WORKSPACE=BankCardKit.xcworkspace
        - IOS_FRAMEWORK_SCHEME="BankCardKit iOS"
        - EXAMPLE_SCHEME="iOS Example"

before_install:
- gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/BankCardKit.xcworkspace -scheme BankCardKit-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- xcodebuild -version
- xcodebuild -showsdks

# Run `pod lib lint` if specified
- if [ $POD_LINT == "YES" ]; then
pod lib lint;
fi
