osx_image: xcode9.2
language: objective-c
branches:
    only:
        - master
env:
    global:
        - LC_CTYPE=en_US.UTF-8
        - LANG=en_US.UTF-8
        - WORKSPACE=BankCardKit.xcworkspace
#        - IOS_FRAMEWORK_SCHEME="BankCardKit iOS"
        - EXAMPLE_SCHEME="BankCardKit-Example"
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/BankCardKit.xcworkspace -scheme BankCardKit-Example -sdk iphonesimulator10.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- xcodebuild -version
- xcodebuild -showsdks
- pod lib lint

